### ISSUE TITLE
Support MSYS2 64-bit platform for windows

### ISSUE THREAD

**Issue by saluber** [korginc/logue-sdk#1]
**Is your feature request related to a problem? Please describe.**
Template and demo project Makefiles broken for 64-bit msys2 / windows environment.

**Describe the solution you'd like**
Fix Makefiles to ensure ZIP tool dir is correctly set for msys2 64-bit windows env.

**Describe alternatives you've considered**
Use 32-bit version of msys2 for building projects or manually fix makefile conditional logic to check for msys2 / windows build flavor more appropriately.

**Additional context**
Makefile expects $(MSYSTEM) to equal "MSYS" for msys2 platform. However, when using the 64-bit version, $(MSYSTEM) is MINGW64. Ideally, a less flakey approach for checking the build env should be used, or the Makefile should be modified at line 31 to check for both cases before overriding ZIP path.
E.g., 
ifneq ($(MSYSTEM), MSYS)
ifneq ($(MSYSTEM), MINGW64)
     ZIP = ....
endif
endif

See:
[Makefile.fixed.txt](https://github.com/korginc/logue-sdk/files/2086534/Makefile.fixed.txt)

**Comment by etienne-korg** [comment]
In 64-bit msys2 installations I have access to MSYSTEM does report MSYS and not MINGW64. 
However if it is the case under some installations the suggested Makefile modification is worth it.
