### ISSUE TITLE
get_gcc_linux.sh does not work on Raspbian

### ISSUE THREAD

**Issue by makingsoundmachines** [korginc/logue-sdk#3]
**Describe the bug**
The script logue-sdk/tools/gcc/get_gcc_linux.sh does not work on Raspbian - it returns "This script is meant for Linux."

**To Reproduce**
1. Install clean Raspian (Raspberry Pi 3 Model B V1.2)
2. Clone logue-sdk.git
3. Run get_gcc_linux.sh

**Expected behavior**
The script should be able to run on Raspberry PI.

I had a look around the web and this let me install a version of gcc-arm-none-eabi:
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
sudo apt-get update
sudo apt-get install gcc-arm-none-eabi

**Desktop (please complete the following information):**
 - OS: Raspbian Stretch With Desktop, Image with desktop based on Debian Stretch
Version: April 2018
Release date: 2018-04-18
Kernel version: 4.14

**Comment by etienne-korg** [comment]
Hi,

Although it was not explicit in the script's output it is only meant for Linux on Intel 32 bit platforms, while Raspberry Pi is Arm based.

If your distribution provides a prebuilt package for gcc-arm-none-eabi version 5-2016-q3 you can use it.
Newer versions of gcc may also work, but this hasn't been tested.

Best,
