### ISSUE TITLE
./logue-cli probe not working

### ISSUE THREAD

**Issue by sqpierce** [korginc/logue-sdk#4]
**Describe the bug**
When I run ```./logue-cli probe``` from command line (Mac OS X) with the Prologue connected, I get an error.

```
Error: API version request timed out.
Error: Prologue handshake failed.
```

**To Reproduce**
```
$ cd logue-sdk/tools/logue-cli
$ ./get_logue_cli_osx.sh

$ ./logue-cli probe
Error: API version request timed out.
Error: Prologue handshake failed.

# Presumably the following shows the Prologue is connected?
$ ./logue-cli probe -l
  Available MIDI inputs:
    in  0: IAC Driver Bus 1
    in  1: IAC Driver IAC Bus 2
    in  2: prologue MIDI IN
    in  3: prologue KBD/KNOB

  Available MIDI ouputs:
    out 0: IAC Driver Bus 1
    out 1: IAC Driver IAC Bus 2
    out 2: prologue MIDI OUT
    out 3: prologue SOUND

# Could these be the wrong MIDI channels?
$ ./logue-cli probe -o 2 -i 2
Error: Search device request timed out.
Prologue handshake failed.
```

**Expected behavior**
I'm not sure exactly what's supposed to happen, but I would presume it would not be 'Error'.

**Screenshots**
https://github.com/sqpierce/logue-sdk/blob/master/screenshot1.png

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Version 10.13.4 (High Sierra)

**Additional context**
I believe I have all the dependencies set up. I was able to compile my program, and when doing ```./logue-cli check -u /path/to/my/unit``` I get a good result 
```
> Parsing unit archive
> Parsing manifest
> Parsing unit binary payload
> Looks okay.
```

Is the Prologue meant to be started in a special mode for this to work? (i.e. hold down 6 and or 8 as when doing software updates?)

Thanks!

**Comment by etienne-korg** [comment]
If the ports are not automatically detected the following should be used:
Input: prologue KBD/KNOB
Output: prologue SOUND

The other two refer to the legacy MIDI ports on the back of the prologue.

**Comment by gekart** [comment]
Tried that with the current version  0.06-0b, doesn't work. Same problem as above.

**Comment by etienne-korg** [comment]
There's a pending update that should fix a dynamic linking issue on OSX. 
Until it gets officially uploaded here's a direct download link:
https://www.dropbox.com/s/kyjexw6l6ydxzi7/logue-cli-osx-0.07-0b.zip?dl=0

**Comment by gekart** [comment]
Yay! Version 0.07 works flawlessly on my XD.

**Comment by gekart** [comment]
@etienne-korg I included it into VSCode https://www.youtube.com/watch?v=JqyhttRtbnI

**Comment by etienne-korg** [comment]
version v0.07-2b is now available via the download scripts so closing this issue.
