### ISSUE TITLE
Question: what is the range of the value parameter for effects?

### ISSUE THREAD

**Issue by schollz** [korginc/logue-sdk#41]
I have a simple question: in the following code what is the range of the value of `valf`? Is it `[-1,1]` or is it `[0,1]`?

```
void DELFX_PARAM(uint8_t index, int32_t value)
{
  const float valf = q31_to_f32(value);
// range of valf = ??
  
...
```

Thanks for any help!

**Comment by hammondeggs** [comment]
valf is the knob position as a float from 0 to 1.

**Comment by schollz** [comment]
Thanks!
