### ISSUE TITLE
MIDI messages callbacks value resolution increase for dtumlogue SDK

### ISSUE THREAD

**Issue by dukesrg** [korginc/logue-sdk#58]
To avoid API changes in future it make sense to increase the resolution for the values passed to the callbacks in this section:
https://github.com/korginc/logue-sdk/blame/master/platform/drumlogue/README.md#L319 in compliance with MIDI 2.0 specs:
Velocity should be 16-bit
Pitch bend, Channel pressure and Aftertouch - all 32-bit

**Comment by dukesrg** [comment]
-

**Comment by etienne-korg** [comment]
drumlogue is not MIDI 2.0 compliant.

If support for MIDI 2.0 is added in the future, or a compliant product uses an API based on the drumlogue's, then optional callbacks aligned with MIDI 2.0 requirements will be added.
The current API will remain aligned with MIDI 1.0 requirements.
