### ISSUE TITLE
Cycling74 ~gen / RNBO example

### ISSUE THREAD

**Issue by suaw3k** [korginc/logue-sdk#86]
**Is your feature request related to a problem? Please describe.**
No available example for building Louge engines using Cycling74 ~gen or RNBO. 

**Describe the solution you'd like**
A simple example along with the documentation of building engines using ~gen and RNBO.

I'm not sure if there is a possibility to export a ~gen or RNBO project and use it as a sound engine for Korg. If so, is there any available documentation with a simple example?

Thanks

**Comment by dromer** [comment]
@suaw3k RNBO would be unlikely due to https://forum.electro-smith.com/t/plans-to-support-rnbo/3131/6

gen~ and hvcc (the pd equivalent of rnbo) would be interesting to have. I've been looking at how the SDK works, but haven't really figured out how the process loop actually works.

**Comment by suaw3k** [comment]
Thanks for explanation
