### ISSUE TITLE
logue-cli not working for minilogue xd

### ISSUE THREAD

**Issue by gekart** [korginc/logue-sdk#9]
get_logue_cli_osx.sh currently fetches:

http://cdn.storage.korg.com/korg_SDK/logue-cli-osx-0.03-0b.zip

That utility does not yet support the minilogue xd.

Pls check

**Comment by gekart** [comment]
@etienne-korg it would be very nice if you could quickly change the strings in the logue-cli for the minilogue xd. That would allow for a super quick dev cycle.

**Comment by etienne-korg** [comment]
Sorry for the long delay about this. Version 0.06-0b is now finally online and supports minilogue xd.
